steps:
  # Build the Go binary
  # - id: Build go binary
  #   name: golang:1.25-trixie
  #   entrypoint: "go"
  #   args: ["build", "-o", "ops", "."]
  #   env:
  #     - "GOOS=linux"
  #     - "CGO_ENABLED=0"
  #     - "GOARCH=amd64"

  # Retrieve the github access token from Secret Manager and inject it as an env variable
  - id: Retrieve GitHub access Token
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        GITHUB_ACCESS_TOKEN=$(gcloud secrets versions access latest --secret="ops-github-access-token")
        echo "export GITHUB_ACCESS_TOKEN=$$GITHUB_ACCESS_TOKEN" >> /workspace/env.sh
        cat /workspace/env.sh

serviceAccount: projects/local-first-476300/serviceAccounts/cloud-build-sa@local-first-476300.iam.gserviceaccount.com

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

tags:
  - development
  - ops
